### ISSUE TITLE
ORM Database creation script not autogenerating tables in postgresql

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-uniqueid#28]
### Pacifica UniqueID version
latest

### Scenario:
trying to autogenerate database schema via ORM python tooling provided

### Steps to Reproduce:
install pacifica-uniqueid with pip
Setup env and configs
attempt to start service script which includes:
`python -c 'from pacifica.uniqueid.orm import create_tables; create_tables()'`

### Expected Result:
if database is blank, create tables as necessary
if database exists, update tables to reflect current schema or close to this result

### Actual Result:
no tables are created

**Comment by GitBytes** [comment]
Found some additional info that should help narrow things down:
```
Nov 21 18:50:28 core pacifica-uniqueid[27612]: """)
Nov 21 18:50:28 core pacifica-uniqueid[27612]: Traceback (most recent call last):
Nov 21 18:50:28 core pacifica-uniqueid[27612]: File "<string>", line 1, in <module>
Nov 21 18:50:28 core pacifica-uniqueid[27612]: ImportError: cannot import name create_tables
```

**Comment by dmlb2000** [comment]
This is done with `database_setup()` right now. but we are moving to the command line tool and haven't done it yet.
