### ISSUE TITLE
Need to complete repo release cut for latest

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-uniqueid#35]
### Pacifica UniqueID version
v0.3.2/other

### Pacifica Core Software versions
pacifica-uniqueid

**Comment by dmlb2000** [comment]
Latest version of the code is 0.3.2 it was tagged it's in pypi.

**Comment by GitBytes** [comment]
Sorry, the list of releases were condensed to the oldest cut for some reason in the GitHub "releases" tab. My mistake, didn't see the expansion link... I did see it out there in pypi.. Cheers!
